// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) 1992-1995 Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and the
// Books Online documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DB.RC
//
#define IDS_DB                          1
#define IDB_DB                          1
#define IDS_DB_PPG                      2
#define IDI_ABOUTDLL                    10
#define IDD_ABOUTBOX_DB                 100
#define IDS_DB_PPG_CAPTION              101
#define IDD_PROPPAGE_DB                 101
#define IDS_PROPERTIESVERB              200
#define IDC_DATASOURCE                  201
#define IDC_TABLES                      202
#define ID_STATIC                       203
#define ID_STATIC2                      204
#define IDC_COLUMNS                     205
#define ID_USERNAME                     206
#define ID_PASSWORD                     207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         207
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
