//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DBGHNDLR.RC
//
#define IDM_ABOUT                       100
#define IDM_OPTIONS_BREAK               1000
#define IDM_OPTIONS_CLEAR               1010

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40014
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
