# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
# ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
# Copyright (C) 1993 - 1995  Microsoft Corporation.  All Rights Reserved.
#
#
# Processor independent makefile

# Nmake macros for building Windows 32-Bit apps
!include <ntwin32.mak>

PROJ = GDIDIB

all: $(PROJ).exe

# Define project specific macros
PROJ_OBJS  = brushdlg.obj client.obj colordlg.obj dibutil.obj filedlg.obj \
             fileio.obj filenew.obj gdidib.obj infodlg.obj palctrl.obj \
             palette.obj pendlg.obj print.obj statbar.obj toolbar.obj
BASE_OBJS  = winmain.obj init.obj misc.obj about.obj dispatch.obj
EXTRA_LIBS = version.lib comctl32.lib
GLOBAL_DEP = globals.h resource.h 
RC_DEP     = resource.h

# Dependencies
winmain.obj:  winmain.c  $(GLOBAL_DEP)
init.obj:     init.c     $(GLOBAL_DEP)
misc.obj:     misc.c     $(GLOBAL_DEP)
about.obj:    about.c    $(GLOBAL_DEP)
dispatch.obj: dispatch.c $(GLOBAL_DEP)
brushdlg.obj: brushdlg.c $(GLOBAL_DEP)
client.obj:   client.c   $(GLOBAL_DEP)
colordlg.obj: colordlg.c $(GLOBAL_DEP)
dibutil.obj:  dibutil.c  $(GLOBAL_DEP)
filedlg.obj:  filedlg.c  $(GLOBAL_DEP)
fileio.obj:   fileio.c   $(GLOBAL_DEP)
filenew.obj:  filenew.c  $(GLOBAL_DEP)
gdidib.obj:   gdidib.c   $(GLOBAL_DEP)
infodlg.obj:  infodlg.c  $(GLOBAL_DEP)
palctrl.obj:  palctrl.c  $(GLOBAL_DEP)
palette.obj:  palette.c  $(GLOBAL_DEP)
pendlg.obj:   pendlg.c   $(GLOBAL_DEP)
print.obj:    print.c    $(GLOBAL_DEP)
statbar.obj:  statbar.c  $(GLOBAL_DEP)
toolbar.obj:  toolbar.c  $(GLOBAL_DEP)




# Inference rule for updating the object files
.c.obj:
  $(cc) $(cdebug) $(cflags4) $(cvars) $*.c

# Build rule for resource file
$(PROJ).res: $(PROJ).rc $(RC_DEP)
    $(rc) $(rcflags) $(rcvars) /fo $(PROJ).res $(PROJ).rc

# Build rule for EXE
$(PROJ).EXE: $(BASE_OBJS) $(PROJ_OBJS) $(PROJ).res
    $(link) $(linkdebug) $(guilflags4) \
    $(BASE_OBJS) $(PROJ_OBJS) $(PROJ).res $(guilibs) $(EXTRA_LIBS) \
    -out:$(PROJ).exe $(MAPFILE)



# Rules for cleaning out those old files
clean:
    del *.bak *.pdb *.obj *.res *.exp *.map *.sbr *.bsc
