# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992-1995 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=STDREG
OBJS= dialog.obj typeinfo.obj columdlg.obj coursset.obj \
   dsectset.obj enrolset.obj instrset.obj sectset.obj stdreg.obj stdset.obj
USES_DB=1
UNICODE=0
!if "$(PLATFORM)" == "M68K" || "$(PLATFORM)" == "MPPC"
MACPROJ=StdReg
MACSIG=STDR
!endif

!include <mfcsamps.mak>
