# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=CTRLTEST
OBJS=ctrltest.obj paredit.obj \
	dertest.obj wclstest.obj paredit2.obj subtest.obj \
	bbutton.obj custlist.obj custmenu.obj \
	spintest.obj spin.obj \
	derpen.obj dlgpen.obj featpen.obj

!include ..\sample_.mak
