//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CTRLTEST.RC
//
#define IDM_TEST_BITMAP_BUTTON1         400
#define IDM_TEST_BITMAP_BUTTON2         401
#define IDM_TEST_BITMAP_BUTTON3         402
#define IDM_TEST_CUSTOM_LIST            403
#define IDM_TEST_CUSTOM_MENU            405
#define IDM_TEST_DERIVED_EDIT           406
#define IDM_TEST_PENEDIT_CODE           407
#define IDM_TEST_PENEDIT_FEATURES       408
#define IDM_TEST_PENEDIT_TEMPLATE       409
#define IDM_TEST_SPIN_EDIT              410
#define IDM_TEST_SUB_EDIT               411
#define IDM_TEST_WNDCLASS_EDIT          412
#define IDD_CUSTOM_LIST                 500
#define IDD_DERIVED_EDIT                501
#define IDD_SUB_EDIT                    505
#define IDD_SUB_PENEDIT                 506
#define IDC_NUMBEROUT                   1000
#define IDC_EDIT1                       2101
#define IDC_EDIT2                       2102
#define IDC_EDIT3                       2103
#define IDC_EDIT4                       2104
#define IDC_LISTBOX1                    2301
#define ID_PREV                         0x8000
#define ID_NEXT                         0x8001

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         57666
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
