// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) 1992-1995 Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by TRACER.RC

#define IDD_PROMPT                      101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDC_BIT0                        256
#define IDC_BIT1                        257
#define IDC_BIT2                        258
#define IDC_BIT3                        259
#define IDC_BIT4                        260
#define IDC_ENABLEALL                   512
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_COMMAND_VALUE         40001
