//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MDIBind.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CONTROLMENU                 129
#define IDR_RDCTYPE                     130
#define IDR_GRIDTYPE                    131
#define IDD_WINDOWLIST                  131
#define IDR_MASKTYPE                    132
#define IDD_DATASOURCE                  132
#define IDC_RDCLIST                     1000
#define IDC_COLUMN                      1001
#define IDC_USER                        1002
#define IDC_PASWORD                     1003
#define IDC_SQL                         1004
#define IDC_DATASRC                     1005
#define ID_WINDOW_BIND                  32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
