//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by AUTOCLIK.RC
//
#define IDR_MAINFRAME                   2
#define IDR_ACLIKTYPE                   3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CHANGE_TEXT                 102
#define IDC_EDIT1                       1000
#define ID_EDIT_CHANGETEXT              32771

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
