//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BindEnrl.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDD_SECTION                     136
#define IDD_COURSE                      137
#define IDD_INSTRUCTOR                  138
#define IDD_STUDENT                     139
#define IDC_DBCOMBO1                    1000
#define IDC_SCHEDULE                    1001
#define IDC_INSTUCTOR                   1002
#define IDC_SECTION                     1003
#define IDC_RDCSECTION                  1004
#define IDC_COURSE                      1005
#define IDC_HOURS                       1006
#define IDC_TITLE                       1007
#define IDC_RDCSTUDENT                  1009
#define IDC_DBGRID1                     1010
#define IDC_RDCINSTUCTOR                1011
#define IDC_RDCSTUDENT2                 1011
#define IDC_DBGRID2                     1012
#define IDC_RDCCOURSE                   1013
#define IDC_DBLIST1                     1019
#define IDC_ROOM                        1029
#define IDC_CAPACITY                    1030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
