# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992-1995 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=OLDBARS
OBJS=oldbars.obj mainfrm.obj oldbadoc.obj oldbavw.obj \
	globals.obj statbar.obj toolbar.obj

!if "$(PLATFORM)"=="M68K" || "$(PLATFORM)"=="MPPC"
MACPROJ=OldBars
MACSIG=OLDB
!endif

!include <mfcsamps.mak>

statbar.cpp: globals.h statbar.h
toolbar.cpp: globals.h toolbar.h
