/*_ LibEtnry.c    */
/* Copyright (C) 1995 by Digital Mars  */
/* All Rights Reserved                                  */
/* $Revision: 1.1.1.1 $  */



/* 
  A reference to __acrtused_dll is generated by the C/C++ compiler
  when a function LibMain is encountered and it was compiled with -W.
*/
char _acrtused_dll = 0;

extern void __far CRTLibEntry();

__declspec(naked) void __far LibEntry()
{
     __asm {
          jmp CRTLibEntry
     }
}


#pragma startaddress(LibEntry)

