//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by STOCKRC.RC
//
#define IDI_ICON1                       101
#define ID_UPDATE                       1003
#define ID_BEEP                         1004
#define ID_MANUAL                       1005
#define ID_AUTO                         1006
#define ID_HELP                         1008
#define ID_LIMIT                        1009
#define ID_STOCK                        1010
#define ID_JITTER                       1011
#define ID_TIME                         1012
#define ID_STOCK2                       1015
#define ID_SERVICE                      1016
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
