# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992-1996 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=EXTBIND
OBJS= extbind.obj mcsdsc.obj modeldlg.obj msacal70.obj msdgrid.obj \
      msmask.obj nwinddlg.obj

USES_DB=1
UNICODE=0

!include <mfcsamps.mak>


