//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ExtBind.rc
//
#define IDC_ADDPUB                      3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAIN_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_NWIND                       129
#define IDB_BITMAP1                     134
#define IDC_NEWTEXT                     1000
#define IDC_TEXT                        1000
#define IDC_LIST                        1001
#define IDC_RDCPUBS                     1002
#define IDC_RDCNWIND                    1003
#define IDC_MASKEDBOX1                  1004
#define IDC_GRIDPUBS                    1005
#define IDC_HIREDATE                    1007
#define IDC_BIRTHDATE                   1008
#define IDC_DATEGROUP                   1009
#define IDC_NAMEGROUP                   1010
#define IDC_MASKEDBOX2                  1010
#define IDC_FIRSTNAME                   1011
#define IDC_MASKEDBOX3                  1011
#define IDC_LASTNAME                    1012
#define IDC_MASKEDBOX4                  1012
#define IDC_GRIDNWIND                   1013
#define IDC_CALNWIND                    1014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
