/*
*  STDINC.H
*
*
*  Standard Include for personal programming Macros
*
*
*/

#ifndef STDINC_H
#define STDINC_H

#define BOOLEAN unsigned char
#define INT int
#define UINT unsigned int
#define SHORT short
#define USHORT unsigned short
#define CHAR char
#define UCHAR unsigned char
#define LONG long
#define ULONG unsigned long
#define BYTE char
#define UBYTE unsigned char

#define FALSE 0
#define TRUE  1
#define NO    0
#define YES   1

/*
* Standard input key scan codes
*/
#define KEY_F1          0x3b00
#define KEY_F2          0x3c00
#define KEY_F3          0x3d00
#define KEY_F4          0x3e00
#define KEY_F5          0x3f00
#define KEY_F6          0x4000
#define KEY_F7          0x4100
#define KEY_F8          0x4200
#define KEY_F9          0x4300
#define KEY_F10         0x4400
#define KEY_F11
#define KEY_F12

#define KEY_SHFT_F1     0x5400
#define KEY_SHFT_F2     0x5500
#define KEY_SHFT_F3     0x5600
#define KEY_SHFT_F4     0x5700
#define KEY_SHRT_F5     0x5800
#define KEY_SHFT_F6     0x5900
#define KEY_SHFT_F7     0x5a00
#define KEY_SHFT_F8     0x5b00
#define KEY_SHFT_F9     0x5c00
#define KEY_SHFT_F10    0x5d00
#define KEY_SHFT_F11
#define KEY_SHFT_F12

#define KEY_ALT_F1      0x5e00
#define KEY_ALT_F2      0x5f00
#define KEY_ALT_F3      0x6000
#define KEY_ALT_F4      0x6100
#define KEY_ALT_F5      0x6200
#define KEY_ALT_F6      0x6300
#define KEY_ALT_F7      0x6400
#define KEY_ALT_F8      0x6500
#define KEY_ALT_F9      0x6600
#define KEY_ALT_F10     0x6700
#define KEY_ALT_F11
#define KEY_ALT_F12

#define KEY_CTRL_F1     0x6800
#define KEY_CTRL_F2     0x6900
#define KEY_CTRL_F3     0x6a00
#define KEY_CTRL_F4     0x6b00
#define KEY_CTRL_F5     0x6c00
#define KEY_CTRL_F6     0x6d00
#define KEY_CTRL_F7     0x6e00
#define KEY_CTRL_F8     0x6f00
#define KEY_CTRL_F9     0x7000
#define KEY_CTRL_F10    0x7100
#define KEY_CTRL_F11
#define KEY_CTRL_F12

#define KEY_ALT_F1     0x5e00
#define KEY_ALT_F2     0x5f00
#define KEY_ALT_F3     0x6000
#define KEY_ALT_F4     0x6100
#define KEY_ALT_F5     0x6200
#define KEY_ALT_F6     0x6300
#define KEY_ALT_F7     0x6400
#define KEY_ALT_F8     0x6500
#define KEY_ALT_F9     0x6600
#define KEY_ALT_F10    0x6700
#define KEY_ALT_F11
#define KEY_ALT_F12

#define KEY_ALT_A      0x1e00
#define KEY_ALT_B      0x3000
#define KEY_ALT_C      0x2e00
#define KEY_ALT_D      0x2000
#define KEY_ALT_E      0x1200
#define KEY_ALT_F      0x2100
#define KEY_ALT_G      0x2200
#define KEY_ALT_H      0x2300
#define KEY_ALT_I      0x1700
#define KEY_ALT_J      0x2400
#define KEY_ALT_K      0x2500
#define KEY_ALT_L      0x2600
#define KEY_ALT_M      0x3200
#define KEY_ALT_N      0x3100
#define KEY_ALT_O      0x1800
#define KEY_ALT_P      0x1900
#define KEY_ALT_Q      0x1000
#define KEY_ALT_R      0x1300
#define KEY_ALT_S      0x1f00
#define KEY_ALT_T      0x1400
#define KEY_ALT_U      0x1600
#define KEY_ALT_V      0x2f00
#define KEY_ALT_W      0x1100
#define KEY_ALT_X      0x2d00
#define KEY_ALT_Y      0x1500
#define KEY_ALT_Z      0x2c00

#define KEY_ENTER      0x1c0d
#define KEY_CTRL_ENTER 0x1c0a
#define KEY_BACKSPACE  0x0e08
#define KEY_CTRL_BS    0x0e7f

#endif
