# Nmake macros for building Win32 applications
!Include <NTWin32.Mak>

# Suffixes
.SUFFIXES: .Lib .Exp .Def .Cpl

# Inference Rules
.C.Obj:
    $(cc) $(cdebug) $(cflags) $(cvars) $*.C
.Def.Lib:
    $(implib) -machine:$(CPU) -def:$*.Def $*.Obj -out:$*.Lib
.Def.Exp:
    $(implib) -machine:$(CPU) -def:$*.Def $*.Obj -out:$*.Lib
.RC.Res:
    $(rc) $(rcvars) -r -fo $*.Res $*.RC
.Obj.Cpl:
    $(link) $(ldebug) $(dlllflags) -subsystem:native -machine:$(CPU)\
       -out:$*.Cpl $** $(guilibs)

# Macro Defines
PROJ=Stereo

# Target List
All: $(PROJ).Cpl

# Source Objects
$(PROJ).Obj: $(PROJ).C $(PROJ).H

# Import/Export Libraries
$(PROJ).Lib $(PROJ).Exp: $(PROJ).Def $(PROJ).Obj

# Resources
$(PROJ).Res: $(PROJ).RC $(PROJ).H Amp.Ico Tape.Ico Tuner.Ico

# Control Panel Applet (Dynamic Link Library)
$(PROJ).Cpl: $(PROJ).Obj $(PROJ).Exp $(PROJ).Res

# Clean Up Everything
CleanAll: clean
    del *.Cpl

# Clean Up Everything Except .Cpl File
Clean:
    del *.Obj
    del *.Lib
    del *.Exp
    del *.Res
