# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992-1995 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=CATALOG2
OBJS=cat2doc.obj    cat2view.obj   catalog2.obj   catsets.obj    colpage.obj \
     mainfrm.obj    settings.obj   tabpage.obj

USES_DB=1

!include <mfcsamps.mak>
