# Nmake macros for building Win32 applications
!Include <NTWin32.Mak>

# Suffixes
.SUFFIXES: .Hpj

# Inference Rules
.C.Obj:
    $(cc) $(cdebug) $(cflags) $(cvars) $*.C
.RC.Res:
    $(rc) $(rcvars) -r -fo $*.Res $*.RC
.Obj.Exe:
    $(link) $(ldebug) $(guilflags) -out:$*.Exe $** $(guilibs)
.Hpj.Hlp:
    -@if exist $*.Ph del $*.Ph
    $(hc) -n $*.Hpj

# Macro Defines
PROJ=UniPut
OBJ1=Display
OBJ2=Status

# Target List
all: $(PROJ).exe $(PROJ).hlp

# Source Objects
$(PROJ).obj: $(PROJ).c $(PROJ).h
$(OBJ1).obj: $(OBJ1).c $(OBJ1).h $(PROJ).h
$(OBJ2).obj: $(OBJ2).c $(PROJ).h

# Resources
$(PROJ).res: $(PROJ).rc $(PROJ).h

# Executables
$(PROJ).exe: $(PROJ).obj $(OBJ1).obj $(OBJ2).obj $(PROJ).Res

# Help Files
$(PROJ).Hlp: $(PROJ).Hpj $(PROJ).Rtf

# Clean Up Everything
CleanAll: clean
    @del *.Exe 2> nul
    @del *.Hlp 2> nul

# Clean Up Everything Except .Exe and .Hlp Files
Clean:
    @del *.Obj 2> nul
    @del *.Res 2> nul
    @del *.Ph  2> nul
    @del *.Err 2> nul
