// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions (including VB)
#include <ole2.h>


#pragma warning ( disable : 4355 )
/*
 *  Warning 4355 warns against using the *this* pointer in a
 *  constructor.  Since we do this frequently, and it is harmless,
 *  we disable the warning.
 */
