# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1996 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=WWWQUOTE
OBJS=wwwquote.obj queries.obj
USRDLL=1

goal: wwwquote.dll

DLL_LINKFLAGS=/dll
!if "$(DEBUG)" == "0"
DLL_LINKFLAGS=$(DLL_LINKFLAGS) /debug:none
!else
DLL_LINKFLAGS=$(DLL_LINKFLAGS) /debug:full /debugtype:cv
!endif

!include <mfcsamps.mak>

wwwquote.dll wwwquote.lib: wwwquote.obj queries.obj wwwquote.res
	link $(DLL_LINKFLAGS) /out:wwwquote.dll /map:wwwquote.map \
	/implib:wwwquote.lib /def:wwwquote.def queries.obj wwwquote.obj \
	wwwquote.res stdafxdv.obj
