//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vcterm.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_INPUTDLG                    102
#define IDR_MAINFRAME                   128
#define IDR_VCTERMTYPE                  129
#define IDD_SETTINGS                    130
#define IDD_CANCELDLG                   131
#define IDC_STATIC1                     1000
#define IDC_EDIT1                       1001
#define IDC_BAUD1                       1010
#define IDC_BAUD2                       1011
#define IDC_BAUD3                       1012
#define IDC_BAUD4                       1013
#define IDC_BAUD5                       1014
#define IDC_BAUD6                       1015
#define IDC_DATABITS1                   1020
#define IDC_DATABITS2                   1021
#define IDC_STOPBITS1                   1022
#define IDC_STOPBITS2                   1023
#define IDC_ECHO1                       1030
#define IDC_ECHO2                       1031
#define IDC_PARITY1                     1040
#define IDC_PARITY2                     1041
#define IDC_PARITY3                     1042
#define IDC_COM1                        1050
#define IDC_COM2                        1051
#define IDC_COM3                        1052
#define IDC_COM4                        1053
#define IDC_FLOW1                       1060
#define IDC_FLOW2                       1061
#define IDC_FLOW3                       1062
#define IDC_FLOW4                       1063
#define ID_FILE_OPENLOG                 32771
#define ID_FILE_CLOSELOG                32772
#define ID_FILE_TRANSMIT                32773
#define ID_PROP_INPUTLEN                32774
#define ID_COMM_OPEN                    32775
#define ID_COMM_SETTINGS                32776
#define ID_COMM_DIAL                    32777
#define ID_COMM_HANGUP                  32778
#define ID_PROP_RTHRESHOLD              32779
#define ID_PROP_STHRESHOLD              32780
#define ID_PROP_PARITYREPLACE           32781
#define ID_PROP_DTRENABLE               32782
#define ID_PROP_CDHOLDING               32783
#define ID_PROP_CTSHOLDING              32784
#define ID_PROP_DSRHOLDING              32785
#define IDS_FILEOPENFAILED              32786
#define IDS_DATASENDFAILED              32789
#define IDS_PHONEPROMPT                 32790
#define IDS_DIALCOMMAND                 32791
#define IDS_INPUTLENPROMPT              32792
#define IDS_RTHRESHOLDPROMPT            32793
#define IDS_STHRESHOLDPROMPT            32794
#define IDS_PARITYREPLACEPROMPT         32795
#define IDS_CDHOLDINGTRUE               32796
#define IDS_CDHOLDINGFALSE              32797
#define IDS_CTSHOLDINGTRUE              32798
#define IDS_CTSHOLDINGFALSE             32799
#define IDS_DSRHOLDINGTRUE              32800
#define IDS_DSRHOLDINGFALSE             32801
#define IDS_SENDING                     32802
#define IDS_RECEIVING                   32803
#define IDS_CTSCHANGE                   32804
#define IDS_DSRCHANGE                   32805
#define IDS_CDCHANGE                    32806
#define IDS_PHONERING                   32807
#define IDS_EOFDETECTED                 32808
#define IDS_BREAKRECEIVED               32809
#define IDS_CTSTIMEOUT                  32810
#define IDS_DSRTIMEOUT                  32811
#define IDS_FRAMEERROR                  32812
#define IDS_OVERRUNERROR                32813
#define IDS_CDTIMEOUT                   32814
#define IDS_RBUFFEROVERFLOW             32815
#define IDS_PARITYERROR                 32816
#define IDS_TBUFFERFULL                 32817
#define IDS_UPDATEDATAFAILED            32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
