//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by TMLRead.rc
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100

#define IDC_PREVFILE                    32000

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_CONTROL_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_COMMAND_VALUE         32768

// Added manually:
//
#define IDC_HYPERLNK                    101
#define IDD_PREFDIALOG                  102
#define ID_PREFS_DEFAULT               3000
#define IDC_PARVSPACE                  3001
#define IDC_MARGIN                     3004
#define IDC_INDENT                     3005
