/**************************************************************************
 *
 *  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 *  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 *  Copyright (c) 1992 - 1994  Microsoft Corporation.  All Rights Reserved.
 *
 **************************************************************************/
/*--------------------------------------------------------------+
| WriteAVI.h - definitions for WriteAVI app			|
|								|
+--------------------------------------------------------------*/

//String Table ID's

#define IDS_APPNAME		1
#define IDS_APPERR		2
#define IDS_VFWTOOOLD		3
#define IDS_INTRO		4
#define IDS_FILENAME		5
#define IDS_WRITEERR		6
#define IDS_TEXTFORMAT		7

