# Nmake macros for building Windows 32-Bit apps

!include <win32.mak>

all: mciplay.exe

OBJS= mciplay.obj

OTHERCLOPTS=-DWIN32_LEAN_AND_MEAN -nologo -I. -I..\include
OTHERRCOPTS=-DWIN32_LEAN_AND_MEAN -I. -I..\include


# Update the resource if necessary

mciplay.res: mciplay.rc mciplay.h mciplay.rcv mciplay.ico
    $(rc) -r -DWIN32 $(OTHERRCOPTS) mciplay.rc



# Update the object file if necessary

mciplay.obj: mciplay.c mciplay.h
    $(cc) $(cdebug) $(cflags) $(cvars) $(OTHERCLOPTS) mciplay.c

# Update the executable file if necessary, and if so, add the resource back in.

mciplay.exe:  $(OBJS) mciplay.res
    $(link) $(linkdebug) $(guilflags) -out:mciplay.exe $(OBJS) mciplay.res $(guilibs) \
	 winmm.lib vfw32.lib

