//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by catalog.rc
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_CATALOG_FORM                101
#define IDC_OWNER                       102
#define IDP_FAILED_OPEN_DATABASE        103
#define IDC_REMARK                      104
#define IDC_TYPE                        105
#define IDC_COLUMNS                     107
#define IDC_NAME                        200

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
