# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1996 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=MFCUCASE
OBJS=mfcucase.obj
NO_PCH=1

goal: mfcucase.dll

DLL_LINKFLAGS=/dll
!if "$(DEBUG)" == "0"
DLL_LINKFLAGS=$(DLL_LINKFLAGS) /debug:none
!else
DLL_LINKFLAGS=$(DLL_LINKFLAGS) /debug:full /debugtype:cv
!endif

!include <mfcsamps.mak>

mfcucase.dll mfcucase.lib: mfcucase.obj mfcucase.res
	link $(DLL_LINKFLAGS) /out:mfcucase.dll /map:mfcucase.map \
	/implib:mfcucase.lib /def:mfcucase.def mfcucase.obj mfcucase.res

