//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by VBCHART.RC
//
#define IDR_MAINFRAME                   2
#define IDR_CHARTDOCTYPE                3
#define IDD_ABOUTBOX                    100
#define IDC_GRID                        101
#define IDD_GRIDENTRY                   101
#define IDC_GRIDEDIT                    102
#define IDC_CHARTLIST                   103

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
