# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992-1995 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=DAOVIEW
OBJS=crack.obj      ctrlext.obj    daoview.obj    daovwdoc.obj   listview.obj   \
     mainfrm.obj    optionsd.obj   treeview.obj   dlgparam.obj   dlgsql.obj     \
     dragitem.obj   renamedl.obj

USES_DB=1

!include <mfcsamps.mak>
