# Nmake macros for building Windows 32-Bit apps

!include <win32.mak>

TARGETNAME =    dseqf32

all: $(TARGETNAME).dll

OBJS=           dseqf.obj factory.obj

OTHERCLOPTS=-DWIN32_LEAN_AND_MEAN -nologo -I. -I..\include
OTHERRCOPTS=-DWIN32_LEAN_AND_MEAN -I. -I..\include


# Update the resource if necessary

handler.res: handler.rc handler.rcv
    $(rc) -r -DWIN32 $(OTHERRCOPTS) handler.rc


# Update the object file if necessary

factory.obj: factory.cpp handler.h
    $(cc) $(cdebug) $(cflags) $(cvarsdll) $(OTHERCLOPTS) factory.cpp

dseqf.obj: dseqf.cpp handler.h handler.rc
    $(cc) $(cdebug) $(cflags) $(cvarsdll) $(OTHERCLOPTS) dseqf.cpp

# Update the dll file if necessary, and if so, add the resource back in.

$(TARGETNAME).dll:  $(OBJS) handler.res
    lib -out:$(@B).lib -def:$(TARGETNAME).def $(OBJS)
     $(link) $(linkdebug) -out:$@ $(dllflags)  \
        $(@B).exp $(OBJS) handler.res $(olelibsdll) \
        vfw32.lib winmm.lib msacm32.lib

