//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tracer.rc
//
#define IDS_WRITE_INI_FILE_FAILED       1
#define IDD_PROMPT                      101
#define IDR_MAINFRAME                   128
#define IDC_BIT0                        256
#define IDC_BIT1                        257
#define IDC_BIT2                        258
#define IDC_BIT3                        259
#define IDC_BIT4                        260
#define IDC_BIT6                        261
#define IDC_ENABLEALL                   512
#define IDC_BIT5                        1000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
