//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SCRIBBLE.RC
//
#define IDD_ABOUTBOX				100
#define IDR_MAINFRAME					128
#define IDR_SCRIBBTYPE					129
#define ID_PEN_THICK_OR_THIN            32772
#define ID_PEN_WIDTHS                   32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS			1
#define _APS_NEXT_RESOURCE_VALUE	130
#define _APS_NEXT_COMMAND_VALUE		32774
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#endif
#endif
