//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by daocont.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DAOCONT_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDB_TREEIMAGE                   129
#define IDD_DIALOG1                     130
#define IDB_BITMAP1                     132
#define IDC_CONNECT_DAO                 1001
#define IDC_TREE1                       1002
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_CONNECT_ODBC                1007
#define IDC_SPIN1                       1011
#define IDC_HOTKEY1                     1012
#define IDC_DAOEDITCTRL1                1013
#define IDC_DAOEDITCTRL2                1014
#define IDC_DAOEDITCTRL3                1015
#define IDC_DAOEDITCTRL4                1016
#define IDC_COLNAME1                    1018
#define IDC_COLNAME2                    1019
#define IDC_COLNAME3                    1020
#define IDC_COLNAME4                    1021
#define IDC_RECNUM                      1022
#define IDC_ACCESSPICTCTRL1             1023
#define IDC_ALLOW_EDITS                 1024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
