# Nmake macros for building Windows 32-Bit apps

!include <win32.mak>

all: mcipuzzl.exe

OBJS= mcipuzzl.obj puzzproc.obj puzzle.obj

OTHERCLOPTS=-DWIN32_LEAN_AND_MEAN -nologo -I. -I..\include
OTHERRCOPTS=-DWIN32_LEAN_AND_MEAN -I. -I..\include


# Update the resource if necessary

mcipuzzl.res: mcipuzzl.rc mcipuzzl.h mcipuzzl.rcv mcipuzzl.ico
    $(rc) -r -DWIN32 $(OTHERRCOPTS) mcipuzzl.rc


# Update the object file if necessary

mcipuzzl.obj: mcipuzzl.c mcipuzzl.h puzzle.h puzzproc.h
    $(cc) $(cdebug) $(cflags) $(cvars) $(OTHERCLOPTS) mcipuzzl.c

puzzle.obj: puzzle.c puzzle.h
    $(cc) $(cdebug) $(cflags) $(cvars) $(OTHERCLOPTS) puzzle.c

puzzproc.obj: puzzproc.c puzzproc.h puzzle.h
    $(cc) $(cdebug) $(cflags) $(cvars) $(OTHERCLOPTS) puzzproc.c


# Update the executable file if necessary, and if so, add the resource back in.

mcipuzzl.exe:  $(OBJS) mcipuzzl.res
    $(link) $(linkdebug) $(guilflags) -out:mcipuzzl.exe $(OBJS) mcipuzzl.res $(guilibs) \
	 winmm.lib vfw32.lib

