//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DFVIEW.RC
//
#define BMP_DOCUMENTS                   101
#define ID_FILE_READ                    102
#define ID_FILE_EXIT                    103
#define BMP_BLANKS                      103
#define ID_TESTS_CREATEDOCFILE          104
#define ID_FILE_CREATEDOCFILE           104
#define ID_FILE_ABOUT                   105
#define ID_LIST_EXPANDALL               107
#define ID_LIST_COLLAPSEALL             108
#define ID_HELP_HELP                    113
#define ID_FILE_CLOSE                   114
#define BMP_FOLDERS                     1000
#define IDC_BM1                         1000
#define BMP_WINDOWS                     1001
#define IDC_BM2                         1001
#define IDC_VERSION                     1001
#define IDC_BM3                         1002
#define IDC_BM4                         1003
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         115
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
