//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DaoEnrol.rc
//
#define IDS_CANNOT_DELETE_COURSE_WITH_SECTION 3
#define IDD_ABOUTBOX                    100
#define IDD_DAOENROL_FORM               101
#define IDD_COURSE_FORM                 102
#define IDP_FAILED_OPEN_DATABASE        103
#define IDC_COURSEID                    109
#define IDC_TITLE                       110
#define IDC_HOURS                       111
#define IDR_MAINFRAME                   128
#define IDR_DAOENRTYPE                  129
#define IDC_COURSELIST                  1001
#define IDC_SECTION                     1002
#define IDC_INSTRUCTOR                  1003
#define IDC_ROOM                        1004
#define IDC_SCHEDULE                    1005
#define IDC_CAPACITY                    1006
#define ID_RECORD_ADD                   32771
#define ID_RECORD_REFRESH               32772
#define ID_RECORD_DELETE                32773
#define ID_FORM_SECTIONS                32775
#define ID_FORM_COURSES                 32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
