/* Copyright (C) 1986-2001 by Digital Mars. $Revision: 1.1.1.1 $ */
#if __SC__ || __RCC__
#pragma once
#endif

#ifndef __STORCLAS_H
#define __STORCLAS_H 1

#define  C_EFCN         -1
#define  C_NULL          0
#define  C_AUTO          1
#define  C_EXT           2
#define  C_STAT          3
#define  C_REG           4
#define  C_EXTDEF        5
#define  C_LABEL         6
#define  C_ULABEL        7
#define  C_MOS           8
#define  C_ARG           9
#define  C_STRTAG        10
#define  C_MOU           11
#define  C_UNTAG         12
#define  C_TPDEF         13
#define  C_USTATIC       14
#define  C_ENTAG         15
#define  C_MOE           16
#define  C_REGPARM	 17
#define  C_FIELD         18
#define  C_BLOCK         100
#define  C_FCN           101
#define  C_EOS           102
#define  C_FILE          103
#define  C_LINE		 104
#define  C_ALIAS	 105
#define  C_HIDDEN	 106
#define  C_SHADOW	 107

#endif

