# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=CONTAIN
OBJS=contain.obj mainfrm.obj contrdoc.obj contrvw.obj cntritem.obj
USES_OLE=1
ROOT=..\..

!include ..\..\sample_.mak


