//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CONTAIN.RC
//
#define IDR_MAINFRAME                   2
#define IDR_CONTRTYPE                 3
#define IDR_CONTRTYPE_CNTR_IP	6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED            	100
#define IDP_FAILED_TO_CREATE			102
#define ID_CANCEL_EDIT					32768

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_COMMAND_VALUE         32771
