# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992-1995 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=ENROLL
ROOT=..\..\..	  
OBJS=enroll.obj enroldoc.obj mainfrm.obj sectform.obj sectset.obj \
	coursset.obj addform.obj crsform.obj

USES_DB=1

!include <mfcsamps.mak>
